package Exception;

public class ExampleFour {

    //Q. print following output

//    next-statement: Inside try block
//    next-statement: Outside of try-catch
}
